<li class="endpoint">
    <ul class="operations">
        <li class="post operation">
            <div class="heading">
                <h3>
                    <span class="http_method"><a href="" class="toggleOperation">post</a></span>
                    <span class="path"><a href="" class="toggleOperation"><?= $endpoint['path']; ?></a></span>
                </h3>

                <ul class="options">
                    <li>
                        <a href="" class="toggleOperation"><?= $endpoint['description']; ?></a>
                    </li>
                </ul>
            </div>

            <div class="content">
                <form accept-charset="UTF-8" class="sandbox">
                    <div style="margin:0;padding:0;display:inline"></div>
                    <h4>Parameters</h4>
                    <table class="fullwidth">
                        <thead>
                            <tr>
                                <th style="width: 100px; max-width: 100px">Parameter</th>
                                <th style="width: 310px; max-width: 310px">Value</th>
                                <th style="width: 200px; max-width: 200px">Description</th>
                                <th style="width: 320px; max-width: 330px">Data Type</th>
                            </tr>
                        </thead>
                        <tbody class="operation-params">
                            <tr>
                                <td class="code required">Array[User]</td>
                                <td><textarea class="body-textarea" placeholder="(required)"
                                              name="Array[User]"></textarea> <br>

                                    <div class="content-type">
                                        <div><label for="contentType">Parameter content type:</label> <select
                                                name="contentType">
                                            <option value="application/json">application/json</option>
                                        </select></div>
                                    </div>
                                </td>
                                <td><strong>List of user object</strong></td>
                                <td><span class="model-signature"><div>
                                    <div>
                                        <ul class="signature-nav">
                                            <li><a class="description-link selected" href="#">Model</a></li>
                                            <li><a class="snippet-link" href="#">Model Schema</a></li>
                                        </ul>
                                        <div>
                                            <div class="signature-container">
                                                <div class="description" style="display: block; "><span
                                                        style="font-weight: bold; color: #000; font-size: 1.1em">Array[User]</span><br><span
                                                        style="font-weight: bold; color: #000; font-size: 1.0em">class User(</span><span>id: long</span>,
                                                    <span>lastName: string</span>, <span>phone: string</span>, <span>username: string</span>,
                                                    <span>email: string</span>, <span>userStatus: int = ['1-registered' or '2-active' or '3-closed'] {User Status}</span>,
                                                    <span>firstName: string</span>, <span>password: string</span><span
                                                            style="font-weight: bold; color: #000; font-size: 1.0em">)</span>
                                                </div>
                                                <div class="snippet" style="display: none; ">
                                                    <pre><code class="json">[ { "<span class="attribute">id</span>":
                                                        <span class="value"><span class="string">"long"</span></span>, "<span
                                                                class="attribute">lastName</span>": <span class="value"><span
                                                                class="string">"string"</span></span>, "<span
                                                                class="attribute">phone</span>": <span
                                                                class="value"><span
                                                                class="string">"string"</span></span>, "<span
                                                                class="attribute">username</span>": <span class="value"><span
                                                                class="string">"string"</span></span>, "<span
                                                                class="attribute">email</span>": <span
                                                                class="value"><span
                                                                class="string">"string"</span></span>, "<span
                                                                class="attribute">userStatus</span>": <span
                                                                class="value"><span class="string">"int"</span></span>,
                                                        "<span class="attribute">firstName</span>": <span class="value"><span
                                                                class="string">"string"</span></span>, "<span
                                                                class="attribute">password</span>": <span class="value"><span
                                                                class="string">"string"</span> }</span> ]</code></pre>
                                                    <small class="notice">Click to set as parameter value</small>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div></span></td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="sandbox_header"><input class="submit" name="commit" type="button" value="Try it out!">
                        <a href="#" class="response_hider" style="display:none">Hide Response</a> <img alt="Throbber"
                                                                                                       class="response_throbber"
                                                                                                       src="images/throbber.gif"
                                                                                                       style="display:none">
                    </div>
                </form>
                <div class="response" style="display:none"><h4>Request URL</h4>

                    <div class="block request_url"></div>
                    <h4>Response Body</h4>

                    <div class="block response_body"></div>
                    <h4>Response Code</h4>

                    <div class="block response_code"></div>
                    <h4>Response Headers</h4>

                    <div class="block response_headers"></div>
                </div>
            </div>
        </li>
    </ul>
</li>
