<li class="resource">
    <div class="heading">
        <h2>
            <a href=""><?= $this->resource['resourcePath'] ?></a>

            <ul class="options">
                <li></li>
            </ul>
        </h2>
    </div>

    <ul class="endpoints">
        <?php foreach($this->resource['apis'] as $endpoint): ?>
            <?= $this->render('swagger-module/documentation/endpoint', array('endpoint' => $endpoint)); ?>
        <?php endforeach; ?>
    </ul>
</li>
